/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimDialogEl: typeof import('./src/components/SimDialogEl/index.vue')['default']
    SimFormErrorMsg: typeof import('./src/components/SimFormErrorMsg/index.vue')['default']
    SimIcon: typeof import('./src/components/SimIcon/index.vue')['default']
  }
}
