/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcumb: typeof import('./library/components/SimHeader/components/breadcumb.vue')['default']
    NavTypePage: typeof import('./library/components/SimThemeDrawer/components/navTypePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimApp: typeof import('./library/components/SimApp/index.vue')['default']
    SimAside: typeof import('./library/components/SimAside/index.vue')['default']
    SimColorPicker: typeof import('./library/components/SimColorPicker/index.vue')['default']
    SimDrawerMenu: typeof import('./library/components/SimDrawerMenu/index.vue')['default']
    SimEcharts: typeof import('./src/components/SimEcharts/index.vue')['default']
    SimError: typeof import('./library/components/SimError/index.vue')['default']
    SimErrorDialog: typeof import('./library/components/SimErrorDialog/index.vue')['default']
    SImFooter: typeof import('./library/components/SImFooter/index.vue')['default']
    SimHeader: typeof import('./library/components/SimHeader/index.vue')['default']
    SimHeaderTools: typeof import('./library/components/SimHeaderTools/index.vue')['default']
    SimIcon: typeof import('./library/components/SimIcon/index.vue')['default']
    SimIconSelector: typeof import('./library/components/SimIconSelector/index.vue')['default']
    SimLanguage: typeof import('./library/components/SimLanguage/index.vue')['default']
    SimLock: typeof import('./library/components/SimLock/index.vue')['default']
    SimLogo: typeof import('./library/components/SimLogo/index.vue')['default']
    SimMainView: typeof import('./library/components/SimMainView/index.vue')['default']
    SimMenu: typeof import('./library/components/SimMenu/index.vue')['default']
    SimMenuItem: typeof import('./library/components/SimMenu/components/simMenuItem.vue')['default']
    SimMenuStatus: typeof import('./library/components/SimMenu/components/simMenuStatus.vue')['default']
    SimRowHeader: typeof import('./library/components/SimRowHeader/index.vue')['default']
    SimSubmenu: typeof import('./library/components/SimMenu/components/simSubmenu.vue')['default']
    SimSvg: typeof import('./library/components/SimSvg/index.vue')['default']
    SimSwitchDark: typeof import('./library/components/SimSwitchDark/index.vue')['default']
    SimTabs: typeof import('./library/components/SimTabs/index.vue')['default']
    SimThemeDrawer: typeof import('./library/components/SimThemeDrawer/index.vue')['default']
    SimUpdate: typeof import('./library/components/SimUpdate/index.vue')['default']
  }
}
