declare module 'element-plus/dist/locale/en.mjs'
declare module 'element-plus/dist/locale/zh-cn.mjs'
declare module 'vue3-excel-editor'
declare module '@vue-office/docx/lib/v3'
declare module '@vue-office/excel/lib/v3'
declare module '@vue-office/pdf/lib/v3'
declare module 'colorthief'
