export const themeConfig: ITheme = {
  // 布局风格 普通布局ordinary  横向布局row   浮动布局float
  layout: 'ordinary',
  // 主题颜色
  themeColor: '#4c7cc3',
  // 菜单风格：卡片，箭头
  menuMode: 'card',
  // 顶部固定
  fixedHeader: true,
  // 是否启动进度条
  isProgress: true,
  // 是否显示标签页
  isTabs: true,
  // 标签页的显示样式
  tabsStyle: '',
  // 标签页的图标
  isTabsIcon: true,
  // 标签页的风格
  tabStyle: 'card',
  // 是否刷新
  isRefresh: true,
  // 手机否显示主题入口
  isTheme: true,
  // 是否显示全屏效果
  isFullPage: true,
  // 是否开启页面动画
  isPageTransition: true,
  // 动画名称
  transitionName: 'fade-in',
  // 是否开启锁屏模式
  isLocked: true,
  // 是否显示主题设置按钮
  isThemeSetting: true,
  // 语言类型zh、en
  i18n: 'zh',
  // 是否显示国际化
  isI18n: true,
  // ui尺寸
  size: 'default',
  // 色弱模式
  colorWeakness: false,
  // 菜单缩放
  collapse: false,
  // 是否显示底部
  isFooter: true,
  // 是否显示debug
  isDebug: true,
  // 是否显示消息
  isNotice: true,
  // 是否显示面包屑
  isBreadcrumb: true,
}
